#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/ezwold

validate_section_ezwol() {
	uci_validate_section ezwol ezwol "${1}" \
		'enabled:bool:0' \
		'port:port:61323' \
		'auth_key:string'
}

start_service() {
	local enabled port auth_key
	
	validate_section_ezwol config || {
		echo "validation failed"
		return 1
	}
	
	[ "$enabled" -eq 0 ] && {
		echo "EzWoL is disabled"
		return 0
	}
	
	[ -z "$auth_key" ] && {
		echo "Authentication key is not set. Please configure it in LuCI or /etc/config/ezwol"
		return 1
	}
	
	procd_open_instance
	procd_set_param command "$PROG" "$port" "$auth_key"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	
	echo "EzWoL started on port $port"
}

service_triggers() {
	procd_add_reload_trigger "ezwol"
	procd_add_validation validate_section_ezwol
}
